<a href="https://colab.research.google.com/github/palettflower/dap-2024/blob/main/les03/rep.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<3>  <12002209> <Алимова Полина Игоревна>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [ ]:
import numpy as np
np.version.version
y = np.random.randint(-50, 50, (10, 10))
print(y)
print(np.min(y))
print(np.max(y))

[[-12  32  26  43 -22   3 -47  46  27 -32]
 [ 12 -23  41 -48 -28  43  47 -37 -34  47]
 [ 47  -5   9 -37 -27  17 -14 -22   6 -15]
 [-30   6  16 -19  38 -38 -40 -25  29 -25]
 [ 33   2  17  42 -19  22  -4  26 -50 -50]
 [-43   4  20  42 -38 -27  -1 -46 -24   9]
 [ 10 -49 -12  15 -43  34  26 -19  43 -18]
 [ 14 -48  24 -24  30 -13 -30 -14   9 -23]
 [  3  -8  42 -45 -38 -26 -50  -6 -43  36]
 [ -3  46  41 -37  25  29 -45 -34  20 -36]]
-50
47


2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [ ]:
import numpy as np
np.version.version
x=np.array([0, 1])
y=np.array([1, 0])
x=np.concatenate([x,x,x,x])
y=np.concatenate([y,y,y,y])
x=np.concatenate([[x],[y],[x],[y]])
print(x)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [ ]:
z = np.arange(11)
print(z)
x1, x2, x3 = np.split(z, [3, 9])
x2=x2*(-1)
print(x2)
np.concatenate([x1, x2, x3])

[ 0  1  2  3  4  5  6  7  8  9 10]
[-3 -4 -5 -6 -7 -8]


array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9, 10])

4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [ ]:
z = np.random.rand(5, 10)
print(z)
s=np.mean(z, axis=1)
s=s.reshape(5,1)
print(s)
print(z-s)

[[0.81792819 0.07070146 0.35971313 0.16602048 0.03456201 0.65974073
  0.55383971 0.1973845  0.91692314 0.30683817]
 [0.12584059 0.11631506 0.28923903 0.93972773 0.44213019 0.6533617
  0.37874244 0.72761328 0.78496958 0.44868403]
 [0.15489536 0.33562234 0.2982357  0.2710958  0.06278232 0.91486553
  0.3244522  0.0883233  0.50836771 0.89351841]
 [0.79728261 0.83086361 0.39840563 0.13856545 0.5322872  0.07501271
  0.52640283 0.70913745 0.88346355 0.25251237]
 [0.27070985 0.4046678  0.17256603 0.70563862 0.62905234 0.09949503
  0.53880242 0.73647033 0.91702463 0.31456749]]
[[0.40836515]
 [0.49066236]
 [0.38521587]
 [0.51439334]
 [0.47889945]]
[[ 0.40956304 -0.33766369 -0.04865202 -0.24234467 -0.37380314  0.25137558
   0.14547456 -0.21098065  0.50855799 -0.10152698]
 [-0.36482178 -0.3743473  -0.20142334  0.44906537 -0.04853217  0.16269933
  -0.11191992  0.23695091  0.29430722 -0.04197833]
 [-0.23032051 -0.04959352 -0.08698017 -0.11412007 -0.32243355  0.52964967
  -0.06076367 -0.29689257  0.1

5. Поменяйте 1 и 2 строки матрицы

In [ ]:
z = np.arange(25).reshape(5,5)
x1, x2, x3 = np.split(z, [1,2])
print(z)
print(x1,x2,x3)
np.concatenate([x2, x1, x3])

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[0 1 2 3 4]] [[5 6 7 8 9]] [[10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [ ]:
z = np.random.random((10,2))
print(z)
x, y = np.split(z, [1], axis=1)
print(x, y)
r=np.sqrt(pow(x,2)+pow(y,2))
tg=np.arctan(y/x)
print(r)
print(tg)
np.concatenate([x,y], axis=1)

[[0.77824455 0.91750605]
 [0.67275291 0.76902188]
 [0.8921606  0.02788715]
 [0.58421999 0.79551479]
 [0.96135206 0.1079664 ]
 [0.03312288 0.15003087]
 [0.70892686 0.26483989]
 [0.003175   0.75245866]
 [0.15266841 0.02924108]
 [0.0372035  0.60732845]]
[[0.77824455]
 [0.67275291]
 [0.8921606 ]
 [0.58421999]
 [0.96135206]
 [0.03312288]
 [0.70892686]
 [0.003175  ]
 [0.15266841]
 [0.0372035 ]] [[0.91750605]
 [0.76902188]
 [0.02788715]
 [0.79551479]
 [0.1079664 ]
 [0.15003087]
 [0.26483989]
 [0.75245866]
 [0.02924108]
 [0.60732845]]
[[1.20311343]
 [1.02175884]
 [0.89259634]
 [0.9869938 ]
 [0.96739575]
 [0.1536437 ]
 [0.75678099]
 [0.75246536]
 [0.15544351]
 [0.60846689]]
[[0.86733809]
 [0.85207036]
 [0.03124782]
 [0.93735916]
 [0.1118382 ]
 [1.35350811]
 [0.35752391]
 [1.56657685]
 [0.18924136]
 [1.50961514]]


array([[0.77824455, 0.91750605],
       [0.67275291, 0.76902188],
       [0.8921606 , 0.02788715],
       [0.58421999, 0.79551479],
       [0.96135206, 0.1079664 ],
       [0.03312288, 0.15003087],
       [0.70892686, 0.26483989],
       [0.003175  , 0.75245866],
       [0.15266841, 0.02924108],
       [0.0372035 , 0.60732845]])

7. Заменить максимальный элемент массива на ноль

In [ ]:
z = np.random.random(10)
x=np.max(z)
print(x)
z==x
z[z==x]=0
print(z)

0.7719255998561364
[0.71554859 0.59888261 0.0276388  0.39076648 0.65095457 0.05202571
 0.42533704 0.5505143  0.         0.54546619]
0.5988826062995998


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [ ]:
z = np.ones(10)
i = np.random.randint(0,len(z),5)
print(z,i)
i=np.unique(i)
print(i)
z[i]=1+z[i]
print(z)
# Напишите ваш код здесь

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] [3 3 9 2 4]
[2 3 4 9]
[1. 1. 2. 2. 2. 1. 1. 1. 1. 2.]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [ ]:
z = np.array([1,2,3,4,5])
print(z)
x=np.zeros(len(z)*4)
x[::4]=z

print(x)
# Напишите ваш код здесь

[1 2 3 4 5]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5. 0. 0. 0.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [ ]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
print(z)
print(v)
s=z-v
print(np.abs(s))
s=np.abs(s)<0.5
print(z[s])


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
67.4503935026881
[67.4503935 66.4503935 65.4503935 64.4503935 63.4503935 62.4503935
 61.4503935 60.4503935 59.4503935 58.4503935 57.4503935 56.4503935
 55.4503935 54.4503935 53.4503935 52.4503935 51.4503935 50.4503935
 49.4503935 48.4503935 47.4503935 46.4503935 45.4503935 44.4503935
 43.4503935 42.4503935 41.4503935 40.4503935 39.4503935 38.4503935
 37.4503935 36.4503935 35.4503935 34.4503935 33.4503935 32.4503935
 31.4503935 30.4503935 29.4503935 28.4503935 27.4503935 26.4503935
 25.4503935 24.4503935 23.4503935 22.4503935 21.4503935 20.4503935
 19.4503935 18.4503935 17.4503935 16.4503935 15.4503935 14.4503935
 13.4503935 12.4503935 11.4503935 10.4503935  9.4503935  8.4503935
  7.450

## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?